apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: main-component
  annotations:
    build.appstudio.openshift.io/request: configure-pac
    build.appstudio.openshift.io/pipeline: '{"name":"docker-build","bundle":"latest"}'
spec:
  application: main-app
  componentName: main-component
  source:
    git:
      url: https://github.com/mmorhun/test-components.git
      revision: main
      context: ./
      dockerfileUrl: Dockerfile
